# Generated by Django 6.1.1 on 2026-09-28 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО преподавателя')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Учёная степень')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Кафедра')),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
        ),
    ]
