# Generated by Django 6.1.1 on 2026-10-01 10:34

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
